In [1]:
import torch
import gpytorch
import botorch
import matplotlib.pyplot as plt
import numpy as np

plt.style.use("bmh")

from tqdm.notebook import tqdm

class Hartmann:
    """Generic Hartmann in 3,4,6 dims on [0,1]^d."""
    _params = {
        3: {
            "alpha": torch.tensor([1.0,1.2,3.0,3.2]),
            "A":     torch.tensor([[3.0,10,30],
                                   [0.1,10,35],
                                   [3.0,10,30],
                                   [0.1,10,35]]),
            "P":     torch.tensor([[3689,1170,2673],
                                   [4699,4387,7470],
                                   [1091,8732,5547],
                                   [381,5743,8828]]) * 1e-4
        },
        4: {
            "alpha": torch.tensor([1.0,1.2,3.0,3.2]),
            "A":     torch.tensor([[10,3,17,3.5],
                                   [0.05,10,17,0.1],
                                   [3,3.5,1.7,10],
                                   [17,8,0.05,10]]),
            "P":     torch.tensor([[1312,1696,5569,124],
                                   [2329,4135,8307,3736],
                                   [2348,1451,3522,2883],
                                   [4047,8828,8732,5743]]) * 1e-4
        },
        6: {
            "alpha": torch.tensor([1.0,1.2,3.0,3.2]),
            "A":     torch.tensor([[10,3,17,3.5,1.7,8],
                                   [0.05,10,17,0.1,8,14],
                                   [3,3.5,1.7,10,17,8],
                                   [17,8,0.05,10,0.1,14]]),
            "P":     torch.tensor([[1312,1696,5569,124,8283,5886],
                                   [2329,4135,8307,3736,1004,9991],
                                   [2348,1451,3522,2883,3047,6650],
                                   [4047,8828,8732,5743,1091,381]]) * 1e-4
        }
    }

    def __init__(self, dim=3):
        assert dim in (3,4,6)
        p = self._params[dim]
        self.alpha, self.A, self.P = p["alpha"], p["A"], p["P"]
        self.bounds = torch.stack([torch.zeros(dim), torch.ones(dim)])

    def __call__(self, x: torch.Tensor) -> torch.Tensor:
        # x: (..., d)
        d = x.size(-1)
        inner = ((x.unsqueeze(-2) - self.P)**2 * self.A).sum(dim=-1)  # (..., 4)
        return -(self.alpha * torch.exp(-inner)).sum(dim=-1)

def visualize_gp_belief_and_policy(model, likelihood, policy=None, next_x=None):
    # Disabled for 3D Hartmann function; kept for compatibility
    pass

class GPModel(gpytorch.models.ExactGP, botorch.models.gpytorch.GPyTorchModel):
    _num_outputs = 1

    def __init__(self, train_x, train_y, likelihood):
        super().__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module = gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel())

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)

def fit_gp_model(train_x, train_y, num_train_iters=500):
    # Declare the GP
    noise = 1e-4

    likelihood = gpytorch.likelihoods.GaussianLikelihood()
    model = GPModel(train_x, train_y, likelihood)
    model.likelihood.noise = noise

    # Train the hyperparameters
    optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
    mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, model)

    model.train()
    likelihood.train()

    for i in tqdm(range(num_train_iters), desc="Training GP"):
        optimizer.zero_grad()

        output = model(train_x)
        loss = -mll(output, train_y)

        loss.backward()
        optimizer.step()

    model.eval()
    likelihood.eval()

    return model, likelihood

# Initialize Hartmann function (3D) and bounds
hartmann = Hartmann(dim=3)
bounds = hartmann.bounds  # [[0, 0, 0], [1, 1, 1]]

# Parameters
n_initial_points = 10
num_queries = 10
num_runs = 10

# Store minimum f(x) for each run
all_min_f_values = []

for run in range(num_runs):
    print(f"\nRun {run + 1}/{num_runs}")
    
    # Set different random seed for each run
    torch.manual_seed(2 + run)
    
    # Initialize with 10 random points in [0, 1]^3
    train_x = torch.rand(size=(n_initial_points, 3))  # Uniformly sampled in [0, 1]^3
    train_y = hartmann(train_x)

    # Print initial points and their function values
    print("Initial points (x1, x2, x3, f(x)):")
    print(torch.hstack([train_x, train_y.unsqueeze(1)]))

    # Fit initial GP model
    model, likelihood = fit_gp_model(train_x, train_y)

    # Track minimum f(x) for this run
    min_f_values = [train_y.min().item()]

    # Run Bayesian optimization
    for i in range(num_queries):
        print(f"Iteration {i}, incumbent x=({train_x[train_y.argmin()].numpy().round(4).tolist()}), f(x)={train_y.min().item():.4f}")

        model, likelihood = fit_gp_model(train_x, train_y)

        policy = botorch.acquisition.analytic.ProbabilityOfImprovement(
            model, best_f=train_y.min(), maximize=False
        )
        
        next_x, acq_val = botorch.optim.optimize_acqf(
            policy,
            bounds=bounds,
            q=1,
            num_restarts=20,
            raw_samples=50,
        )

        next_y = hartmann(next_x)

        # Ensure next_y is 1D with shape (1,)
        next_y = next_y.unsqueeze(0) if next_y.dim() == 0 else next_y

        train_x = torch.cat([train_x, next_x])
        train_y = torch.cat([train_y, next_y])
        
        # Store the minimum f(x)
        min_f_values.append(train_y.min().item())

    # Store results for this run
    all_min_f_values.append(min_f_values)

    # Plot minimum f(x) vs iteration for this run
    plt.figure(figsize=(8, 6))
    plt.plot(range(num_queries + 1), min_f_values, marker='o', linestyle='-', color='b')
    plt.xlabel('Iteration')
    plt.ylabel('Minimum f(x)')
    plt.title(f'Minimum f(x) vs Iteration (Run {run + 1})')
    plt.grid(True)
    plt.savefig(f'min_f_vs_iteration_run_{run + 1}.png')
    plt.close()

# Convert to numpy array for easier computation
all_min_f_values = np.array(all_min_f_values)  # Shape: (num_runs, num_queries + 1)

# Compute mean, std, and 95% CI
mean_f = np.mean(all_min_f_values, axis=0)
std_f = np.std(all_min_f_values, axis=0)
ci_95 = 1.96 * std_f / np.sqrt(num_runs)  # 95% CI: z=1.96 for normal distribution

# Plot convergence with mean, std, and CI
plt.figure(figsize=(10, 6))
iterations = range(num_queries + 1)

# Plot mean
plt.plot(iterations, mean_f, marker='o', linestyle='-', color='b', label='Mean Minimum f(x)')

# Plot 95% CI
plt.fill_between(
    iterations,
    mean_f - ci_95,
    mean_f + ci_95,
    color='b',
    alpha=0.2,
    label='95% Confidence Interval'
)

# Plot mean ± std
plt.fill_between(
    iterations,
    mean_f - std_f,
    mean_f + std_f,
    color='g',
    alpha=0.1,
    label='Mean ± Std'
)

plt.xlabel('Iteration')
plt.ylabel('Minimum f(x)')
plt.title('Convergence Plot: Mean, Std, and 95% CI over 10 Runs (Hartmann 3D)')
plt.grid(True)
plt.legend()
plt.savefig('convergence_plot.png')
plt.close()


Run 1/10
Initial points (x1, x2, x3, f(x)):
tensor([[ 6.1470e-01,  3.8101e-01,  6.3711e-01, -1.1243e+00],
        [ 4.7446e-01,  7.1359e-01,  6.1904e-01, -1.9210e+00],
        [ 4.4253e-01,  9.5769e-02,  6.1416e-01, -2.5620e-01],
        [ 5.7328e-02,  5.6571e-01,  5.3323e-01, -1.3994e+00],
        [ 3.9005e-01,  9.0885e-01,  5.3337e-01, -2.3471e+00],
        [ 7.0734e-01,  7.1160e-01,  2.0503e-01, -3.8577e-02],
        [ 3.0778e-01,  9.8086e-01,  1.0261e-02, -4.0440e-04],
        [ 4.6604e-01,  4.6038e-01,  8.5465e-01, -3.5052e+00],
        [ 4.5247e-01,  6.3166e-01,  4.7600e-01, -1.0673e+00],
        [ 2.2003e-01,  2.1660e-01,  2.5708e-01, -8.4754e-01]])


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

/opt/anaconda3/envs/mybo/lib/python3.10/site-packages/gpytorch/lazy/triangular_lazy_tensor.py:130: UserWarning: torch.triangular_solve is deprecated in favor of torch.linalg.solve_triangularand will be removed in a future PyTorch release.
torch.linalg.solve_triangular has its arguments reversed and does not return a copy of one of the inputs.
X = torch.triangular_solve(B, A).solution
should be replaced with
X = torch.linalg.solve_triangular(A, B). (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp:2261.)
  res = torch.triangular_solve(right_tensor, self.evaluate(), upper=self.upper).solution


Iteration 0, incumbent x=([0.4659999907016754, 0.4603999853134155, 0.8547000288963318]), f(x)=-3.5052


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 1, incumbent x=([0.4659999907016754, 0.4603999853134155, 0.8547000288963318]), f(x)=-3.5052


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 2, incumbent x=([0.46709999442100525, 0.4652000069618225, 0.8449000120162964]), f(x)=-3.5355


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 3, incumbent x=([0.46380001306533813, 0.4778999984264374, 0.8330000042915344]), f(x)=-3.5802


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 4, incumbent x=([0.4555000066757202, 0.49480000138282776, 0.8251000046730042]), f(x)=-3.6224


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 5, incumbent x=([0.44530001282691956, 0.5081999897956848, 0.8235999941825867]), f(x)=-3.6605


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 6, incumbent x=([0.43130001425743103, 0.5200999975204468, 0.8246999979019165]), f(x)=-3.6989


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 7, incumbent x=([0.41260001063346863, 0.5295000076293945, 0.8245000243186951]), f(x)=-3.7200


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 8, incumbent x=([0.41260001063346863, 0.5295000076293945, 0.8245000243186951]), f(x)=-3.7200


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 9, incumbent x=([0.4065999984741211, 0.5446000099182129, 0.829200029373169]), f(x)=-3.7578


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]


Run 2/10
Initial points (x1, x2, x3, f(x)):
tensor([[ 4.2635e-03,  1.0557e-01,  2.8584e-01, -6.6446e-01],
        [ 2.6955e-02,  4.7161e-01,  6.0116e-02, -5.5622e-02],
        [ 7.7187e-01,  7.4370e-01,  5.9442e-01, -9.7982e-01],
        [ 8.8786e-01,  4.5103e-01,  7.9949e-01, -3.0886e+00],
        [ 1.4984e-01,  4.0147e-01,  5.4177e-02, -9.8860e-02],
        [ 4.5941e-01,  1.7561e-01,  9.4918e-01, -6.9345e-01],
        [ 8.4732e-01,  8.7486e-01,  6.4831e-01, -7.5250e-01],
        [ 2.1476e-01,  9.4930e-01,  1.2109e-02, -5.2908e-04],
        [ 1.8088e-01,  1.8772e-01,  2.9274e-01, -8.4295e-01],
        [ 5.9970e-01,  1.2126e-01,  1.1480e-01, -4.2415e-01]])


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 0, incumbent x=([0.8878999948501587, 0.45100000500679016, 0.7994999885559082]), f(x)=-3.0886


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 1, incumbent x=([0.8967000246047974, 0.4429999887943268, 0.8069999814033508]), f(x)=-3.0955


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 2, incumbent x=([0.8967000246047974, 0.4429999887943268, 0.8069999814033508]), f(x)=-3.0955


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 3, incumbent x=([0.8967000246047974, 0.4429999887943268, 0.8069999814033508]), f(x)=-3.0955


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 4, incumbent x=([0.88919997215271, 0.4661000072956085, 0.819100022315979]), f(x)=-3.2840


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 5, incumbent x=([0.8805999755859375, 0.5217000246047974, 0.8585000038146973]), f(x)=-3.5621


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 6, incumbent x=([0.8805999755859375, 0.5217000246047974, 0.8585000038146973]), f(x)=-3.5621


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 7, incumbent x=([0.8844000101089478, 0.5376999974250793, 0.8567000031471252]), f(x)=-3.5822


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 8, incumbent x=([0.8844000101089478, 0.5376999974250793, 0.8567000031471252]), f(x)=-3.5822


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 9, incumbent x=([0.8844000101089478, 0.5376999974250793, 0.8567000031471252]), f(x)=-3.5822


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]


Run 3/10
Initial points (x1, x2, x3, f(x)):
tensor([[ 0.5596,  0.5591,  0.0915, -0.0512],
        [ 0.2100,  0.0072,  0.0390, -0.1720],
        [ 0.9929,  0.9131,  0.6186, -0.4004],
        [ 0.9744,  0.3189,  0.2148, -0.2044],
        [ 0.9263,  0.4735,  0.5949, -0.7464],
        [ 0.7956,  0.7635,  0.2137, -0.0279],
        [ 0.3066,  0.0386,  0.5220, -0.1781],
        [ 0.3207,  0.6074,  0.5233, -1.4589],
        [ 0.9263,  0.5431,  0.7506, -2.6848],
        [ 0.6578,  0.9436,  0.2921, -0.1472]])


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 0, incumbent x=([0.9262999892234802, 0.5430999994277954, 0.7505999803543091]), f(x)=-2.6848


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 1, incumbent x=([0.9258000254631042, 0.5519000291824341, 0.7675999999046326]), f(x)=-2.9046


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 2, incumbent x=([0.904699981212616, 0.5741999745368958, 0.843999981880188]), f(x)=-3.5361


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 3, incumbent x=([0.904699981212616, 0.5741999745368958, 0.843999981880188]), f(x)=-3.5361


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 4, incumbent x=([0.8998000025749207, 0.5769000053405762, 0.8568000197410583]), f(x)=-3.5519


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 5, incumbent x=([0.8884000182151794, 0.5674999952316284, 0.8544999957084656]), f(x)=-3.5726


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 6, incumbent x=([0.8777999877929688, 0.5598000288009644, 0.8532000184059143]), f(x)=-3.5860


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 7, incumbent x=([0.8702999949455261, 0.555400013923645, 0.8521999716758728]), f(x)=-3.5924


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 8, incumbent x=([0.8640000224113464, 0.5569000244140625, 0.8496000170707703]), f(x)=-3.5927


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 9, incumbent x=([0.8633999824523926, 0.5569999814033508, 0.8495000004768372]), f(x)=-3.5929


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]


Run 4/10
Initial points (x1, x2, x3, f(x)):
tensor([[ 8.3025e-01,  1.2611e-01,  9.0747e-01, -5.7579e-01],
        [ 8.1993e-01,  9.2010e-01,  1.1665e-01, -2.4724e-03],
        [ 1.6439e-01,  7.3792e-01,  3.3265e-02, -4.3199e-03],
        [ 9.9418e-01,  6.0643e-01,  5.6457e-01, -5.0039e-01],
        [ 7.2412e-02,  6.5934e-01,  7.1501e-01, -2.6864e+00],
        [ 5.7933e-01,  9.8093e-01,  6.5016e-01, -1.1820e+00],
        [ 5.6634e-02,  9.2011e-01,  6.6976e-01, -2.2485e+00],
        [ 2.6147e-01,  4.0715e-02,  7.8504e-01, -3.6608e-01],
        [ 9.7516e-01,  9.0344e-02,  5.2733e-01, -1.1162e-01],
        [ 6.7939e-01,  2.6388e-01,  3.9060e-01, -4.0538e-01]])


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 0, incumbent x=([0.07240000367164612, 0.6593000292778015, 0.7149999737739563]), f(x)=-2.6864


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 1, incumbent x=([0.06849999725818634, 0.6736999750137329, 0.7246999740600586]), f(x)=-2.7192


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 2, incumbent x=([0.05779999867081642, 0.692300021648407, 0.7588000297546387]), f(x)=-2.8577


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 3, incumbent x=([0.04500000178813934, 0.7192999720573425, 0.839900016784668]), f(x)=-3.0318


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 4, incumbent x=([0.04500000178813934, 0.7192999720573425, 0.839900016784668]), f(x)=-3.0318


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 5, incumbent x=([0.04500000178813934, 0.7192999720573425, 0.839900016784668]), f(x)=-3.0318


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 6, incumbent x=([0.027799999341368675, 0.7073000073432922, 0.8337000012397766]), f(x)=-3.1200


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 7, incumbent x=([0.010599999688565731, 0.6984999775886536, 0.8337000012397766]), f(x)=-3.1884


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 8, incumbent x=([0.0, 0.6934999823570251, 0.8375999927520752]), f(x)=-3.2340


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 9, incumbent x=([0.0, 0.6822999715805054, 0.829800009727478]), f(x)=-3.2986


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]


Run 5/10
Initial points (x1, x2, x3, f(x)):
tensor([[ 0.5722,  0.5539,  0.9868, -2.2629],
        [ 0.6080,  0.2347,  0.4492, -0.3259],
        [ 0.6743,  0.7480,  0.5601, -1.1783],
        [ 0.1674,  0.3333,  0.4648, -0.3679],
        [ 0.6332,  0.7692,  0.2147, -0.0474],
        [ 0.7815,  0.8644,  0.6052, -0.8993],
        [ 0.3650,  0.2536,  0.1642, -0.6038],
        [ 0.2833,  0.3858,  0.8337, -2.9679],
        [ 0.6173,  0.3923,  0.1878, -0.3246],
        [ 0.8375,  0.2109,  0.4282, -0.2434]])


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 0, incumbent x=([0.2833000123500824, 0.38580000400543213, 0.8337000012397766]), f(x)=-2.9679


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 1, incumbent x=([0.2897000014781952, 0.3917999863624573, 0.8495000004768372]), f(x)=-3.0223


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 2, incumbent x=([0.3003999888896942, 0.40209999680519104, 0.8744999766349792]), f(x)=-3.0392


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 3, incumbent x=([0.3003999888896942, 0.40209999680519104, 0.8744999766349792]), f(x)=-3.0392


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 4, incumbent x=([0.3003999888896942, 0.40209999680519104, 0.8744999766349792]), f(x)=-3.0392


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 5, incumbent x=([0.32440000772476196, 0.48820000886917114, 0.8810999989509583]), f(x)=-3.5939


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 6, incumbent x=([0.32510000467300415, 0.5109999775886536, 0.8662999868392944]), f(x)=-3.7491


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 7, incumbent x=([0.3260999917984009, 0.5376999974250793, 0.8486999869346619]), f(x)=-3.8257


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 8, incumbent x=([0.3260999917984009, 0.5376999974250793, 0.8486999869346619]), f(x)=-3.8257


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 9, incumbent x=([0.3260999917984009, 0.5376999974250793, 0.8486999869346619]), f(x)=-3.8257


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]


Run 6/10
Initial points (x1, x2, x3, f(x)):
tensor([[ 0.5349,  0.1988,  0.6592, -0.6695],
        [ 0.6569,  0.2328,  0.4251, -0.3568],
        [ 0.2071,  0.6297,  0.3653, -0.6047],
        [ 0.8513,  0.8549,  0.5509, -0.6561],
        [ 0.2868,  0.2063,  0.4451, -0.4025],
        [ 0.3593,  0.7204,  0.0731, -0.0103],
        [ 0.9699,  0.1078,  0.8829, -0.5381],
        [ 0.4132,  0.7572,  0.6948, -2.1537],
        [ 0.5209,  0.5932,  0.8797, -3.6588],
        [ 0.6286,  0.7653,  0.1132, -0.0094]])


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 0, incumbent x=([0.5209000110626221, 0.5932000279426575, 0.8797000050544739]), f(x)=-3.6588


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 1, incumbent x=([0.5209000110626221, 0.5932000279426575, 0.8797000050544739]), f(x)=-3.6588


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 2, incumbent x=([0.515500009059906, 0.5982000231742859, 0.8568999767303467]), f(x)=-3.7030


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 3, incumbent x=([0.515500009059906, 0.5982000231742859, 0.8568999767303467]), f(x)=-3.7030


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 4, incumbent x=([0.515500009059906, 0.5982000231742859, 0.8568999767303467]), f(x)=-3.7030


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 5, incumbent x=([0.515500009059906, 0.5982000231742859, 0.8568999767303467]), f(x)=-3.7030


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 6, incumbent x=([0.5044000148773193, 0.5773000121116638, 0.8428000211715698]), f(x)=-3.7432


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 7, incumbent x=([0.4950999915599823, 0.5615000128746033, 0.8395000100135803]), f(x)=-3.7585


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 8, incumbent x=([0.37070000171661377, 0.5523999929428101, 0.838100016117096]), f(x)=-3.8031


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 9, incumbent x=([0.37070000171661377, 0.5523999929428101, 0.838100016117096]), f(x)=-3.8031


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]


Run 7/10
Initial points (x1, x2, x3, f(x)):
tensor([[ 5.9793e-01,  8.4530e-01,  9.4641e-01, -1.3631e+00],
        [ 2.9653e-01,  5.1380e-01,  6.4435e-01, -1.7867e+00],
        [ 8.9906e-01,  1.4089e-02,  5.7845e-01, -9.8360e-02],
        [ 1.2181e-01,  9.1809e-01,  6.8053e-01, -2.1638e+00],
        [ 2.0002e-01,  1.1211e-01,  1.9484e-03, -1.1101e-01],
        [ 8.9283e-01,  8.0471e-01,  2.5468e-01, -3.4382e-02],
        [ 4.6830e-01,  1.6823e-01,  1.7126e-01, -7.1723e-01],
        [ 5.1032e-01,  1.0682e-01,  5.9115e-01, -2.3382e-01],
        [ 7.8927e-01,  8.5407e-02,  3.6789e-01, -4.3292e-01],
        [ 4.7609e-01,  6.3862e-01,  4.4802e-01, -8.8419e-01]])


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 0, incumbent x=([0.121799997985363, 0.9180999994277954, 0.6804999709129333]), f(x)=-2.1638


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 1, incumbent x=([0.12439999729394913, 0.8755000233650208, 0.6969000101089478]), f(x)=-2.1807


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 2, incumbent x=([0.12839999794960022, 0.8310999870300293, 0.7113000154495239]), f(x)=-2.2446


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 3, incumbent x=([0.1347000002861023, 0.7621999979019165, 0.7301999926567078]), f(x)=-2.4575


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 4, incumbent x=([0.1379999965429306, 0.7312999963760376, 0.736299991607666]), f(x)=-2.5907


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 5, incumbent x=([0.14830000698566437, 0.6568999886512756, 0.7490000128746033]), f(x)=-2.9354


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 6, incumbent x=([0.1476999968290329, 0.6273000240325928, 0.756600022315979]), f(x)=-3.0899


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 7, incumbent x=([0.14730000495910645, 0.6062999963760376, 0.7601000070571899]), f(x)=-3.1727


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 8, incumbent x=([0.1412999927997589, 0.5651000142097473, 0.779699981212616]), f(x)=-3.4301


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 9, incumbent x=([0.1281999945640564, 0.5217000246047974, 0.8194000124931335]), f(x)=-3.7302


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]


Run 8/10
Initial points (x1, x2, x3, f(x)):
tensor([[ 0.6558,  0.3020,  0.4799, -0.2693],
        [ 0.7774,  0.9180,  0.9310, -0.9048],
        [ 0.2604,  0.9534,  0.3804, -1.0576],
        [ 0.4104,  0.9510,  0.5686, -2.1906],
        [ 0.1381,  0.2069,  0.5139, -0.2710],
        [ 0.4850,  0.5193,  0.3468, -0.3152],
        [ 0.4477,  0.6316,  0.6947, -2.2940],
        [ 0.8215,  0.9111,  0.7315, -0.8131],
        [ 0.4468,  0.0725,  0.9196, -0.3526],
        [ 0.7834,  0.9715,  0.5964, -0.7276]])


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 0, incumbent x=([0.44769999384880066, 0.631600022315979, 0.6947000026702881]), f(x)=-2.2940


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 1, incumbent x=([0.44339999556541443, 0.6621999740600586, 0.7026000022888184]), f(x)=-2.3281


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 2, incumbent x=([0.44339999556541443, 0.6621999740600586, 0.7026000022888184]), f(x)=-2.3281


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 3, incumbent x=([0.4478999972343445, 0.6330999732017517, 0.7368000149726868]), f(x)=-2.7031


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 4, incumbent x=([0.4325999915599823, 0.6136000156402588, 0.8194000124931335]), f(x)=-3.5671


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 5, incumbent x=([0.4325999915599823, 0.6136000156402588, 0.8194000124931335]), f(x)=-3.5671


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 6, incumbent x=([0.42160001397132874, 0.6047999858856201, 0.8579000234603882]), f(x)=-3.7182


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 7, incumbent x=([0.42160001397132874, 0.6047999858856201, 0.8579000234603882]), f(x)=-3.7182


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 8, incumbent x=([0.42160001397132874, 0.6047999858856201, 0.8579000234603882]), f(x)=-3.7182


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 9, incumbent x=([0.42160001397132874, 0.6047999858856201, 0.8579000234603882]), f(x)=-3.7182


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]


Run 9/10
Initial points (x1, x2, x3, f(x)):
tensor([[ 0.4581,  0.4829,  0.3125, -0.3205],
        [ 0.6150,  0.2139,  0.4118, -0.4299],
        [ 0.6938,  0.9693,  0.6178, -0.9654],
        [ 0.3304,  0.5479,  0.4440, -0.7299],
        [ 0.7041,  0.5573,  0.6959, -2.0553],
        [ 0.9849,  0.2924,  0.4823, -0.1537],
        [ 0.6150,  0.4967,  0.4521, -0.3764],
        [ 0.0575,  0.0687,  0.0501, -0.1773],
        [ 0.0108,  0.0343,  0.1212, -0.3351],
        [ 0.0490,  0.0310,  0.7192, -0.2857]])


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 0, incumbent x=([0.7041000127792358, 0.5572999715805054, 0.695900022983551]), f(x)=-2.0553


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 1, incumbent x=([0.7085000276565552, 0.5605999827384949, 0.7139000296592712]), f(x)=-2.2952


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 2, incumbent x=([0.7354999780654907, 0.5906000137329102, 0.8385000228881836]), f(x)=-3.5810


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 3, incumbent x=([0.7387999892234802, 0.5949000120162964, 0.8547999858856201]), f(x)=-3.6015


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 4, incumbent x=([0.7387999892234802, 0.5949000120162964, 0.8547999858856201]), f(x)=-3.6015


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 5, incumbent x=([0.7387999892234802, 0.5949000120162964, 0.8547999858856201]), f(x)=-3.6015


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 6, incumbent x=([0.7387999892234802, 0.5949000120162964, 0.8547999858856201]), f(x)=-3.6015


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 7, incumbent x=([0.7387999892234802, 0.5949000120162964, 0.8547999858856201]), f(x)=-3.6015


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 8, incumbent x=([0.7387999892234802, 0.5949000120162964, 0.8547999858856201]), f(x)=-3.6015


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 9, incumbent x=([0.7354999780654907, 0.5949000120162964, 0.8571000099182129]), f(x)=-3.6041


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]


Run 10/10
Initial points (x1, x2, x3, f(x)):
tensor([[ 0.1490,  0.4866,  0.9857, -2.2040],
        [ 0.1684,  0.5839,  0.6936, -2.5045],
        [ 0.5831,  0.1284,  0.5721, -0.2309],
        [ 0.9248,  0.2693,  0.7825, -1.6671],
        [ 0.2719,  0.4632,  0.7671, -3.0661],
        [ 0.5024,  0.1025,  0.7600, -0.5867],
        [ 0.8035,  0.7653,  0.8709, -2.3550],
        [ 0.7231,  0.8364,  0.5820, -1.0936],
        [ 0.8395,  0.0595,  0.4315, -0.2311],
        [ 0.4425,  0.2622,  0.6301, -0.7303]])


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 0, incumbent x=([0.2718999981880188, 0.46320000290870667, 0.7670999765396118]), f(x)=-3.0661


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 1, incumbent x=([0.26350000500679016, 0.4729999899864197, 0.7807000279426575]), f(x)=-3.2517


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 2, incumbent x=([0.23520000278949738, 0.5156999826431274, 0.8431000113487244]), f(x)=-3.7946


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 3, incumbent x=([0.24070000648498535, 0.536899983882904, 0.8554999828338623]), f(x)=-3.8405


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 4, incumbent x=([0.24220000207424164, 0.5462999939918518, 0.8587999939918518]), f(x)=-3.8462


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 5, incumbent x=([0.24279999732971191, 0.5491999983787537, 0.8587999939918518]), f(x)=-3.8477


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 6, incumbent x=([0.24269999563694, 0.5507000088691711, 0.8586999773979187]), f(x)=-3.8484


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 7, incumbent x=([0.24240000545978546, 0.5515000224113464, 0.8583999872207642]), f(x)=-3.8491


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 8, incumbent x=([0.24070000648498535, 0.5525000095367432, 0.8578000068664551]), f(x)=-3.8503


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 9, incumbent x=([0.23770000040531158, 0.5537999868392944, 0.8567000031471252]), f(x)=-3.8520


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]