In [11]:
import torch
import gpytorch
import botorch
import matplotlib.pyplot as plt
import numpy as np

plt.style.use("bmh")

from tqdm.notebook import tqdm

class Branin:
    """Branin-Hoo f(x1,x2) on [−5,10]×[0,15]"""
    def __init__(self):
        self.bounds = torch.tensor([[-5.0, 0.0], [10.0, 15.0]])
        # recommended constants
        self.a, self.b = 1.0, 5.1/(4*torch.pi**2)
        self.c, self.r = 5.0/torch.pi, 6.0
        self.s, self.t = 10.0, 1.0/(8*torch.pi)
    def __call__(self, x: torch.Tensor) -> torch.Tensor:
        x1, x2 = x[...,0], x[...,1]
        term1 = self.a*(x2 - self.b*x1**2 + self.c*x1 - self.r)**2
        term2 = self.s*(1 - self.t)*torch.cos(x1) + self.s
        return (term1 + term2).squeeze(-1)

def visualize_gp_belief_and_policy(model, likelihood, policy=None, next_x=None):
    # Disabled for 2D Branin function; kept for compatibility
    pass

class GPModel(gpytorch.models.ExactGP, botorch.models.gpytorch.GPyTorchModel):
    _num_outputs = 1

    def __init__(self, train_x, train_y, likelihood):
        super().__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module = gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel())

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)

def fit_gp_model(train_x, train_y, num_train_iters=500):
    # Declare the GP
    noise = 1e-4

    likelihood = gpytorch.likelihoods.GaussianLikelihood()
    model = GPModel(train_x, train_y, likelihood)
    model.likelihood.noise = noise

    # Train the hyperparameters
    optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
    mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, model)

    model.train()
    likelihood.train()

    for i in tqdm(range(num_train_iters), desc="Training GP"):
        optimizer.zero_grad()

        output = model(train_x)
        loss = -mll(output, train_y)

        loss.backward()
        optimizer.step()

    model.eval()
    likelihood.eval()

    return model, likelihood

# Initialize Branin function and bounds
branin = Branin()
bounds = branin.bounds  # [[-5, 0], [10, 15]]

# Parameters
n_initial_points = 10
num_queries = 20
num_runs = 10

# Store minimum f(x) for each run
all_min_f_values = []

for run in range(num_runs):
    print(f"\nRun {run + 1}/{num_runs}")
    
    # Set different random seed for each run
    torch.manual_seed(2 + run)
    
    # Initialize with 10 random points in [-5, 10] x [0, 15]
    train_x = torch.rand(size=(n_initial_points, 2))
    train_x = bounds[0] + (bounds[1] - bounds[0]) * train_x  # Scale to bounds
    train_y = branin(train_x)

    # Print initial points and their function values
    print("Initial points (x1, x2, f(x)):")
    print(torch.hstack([train_x, train_y.unsqueeze(1)]))

    # Fit initial GP model
    model, likelihood = fit_gp_model(train_x, train_y)

    # Track minimum f(x) for this run
    min_f_values = [train_y.min().item()]

    # Run Bayesian optimization
    for i in range(num_queries):
        print(f"Iteration {i}, incumbent x=({train_x[train_y.argmin()][0].item():.4f}, {train_x[train_y.argmin()][1].item():.4f}), f(x)={train_y.min().item():.4f}")

        model, likelihood = fit_gp_model(train_x, train_y)

        policy = botorch.acquisition.analytic.ProbabilityOfImprovement(
            model, best_f=train_y.min(), maximize=False
        )
        
        next_x, acq_val = botorch.optim.optimize_acqf(
            policy,
            bounds=bounds,
            q=1,
            num_restarts=20,
            raw_samples=50,
        )

        next_y = branin(next_x)

        # Ensure next_y is 1D with shape (1,)
        next_y = next_y.unsqueeze(0) if next_y.dim() == 0 else next_y

        train_x = torch.cat([train_x, next_x])
        train_y = torch.cat([train_y, next_y])
        
        # Store the minimum f(x)
        min_f_values.append(train_y.min().item())

    # Store results for this run
    all_min_f_values.append(min_f_values)

    # Plot minimum f(x) vs iteration for this run
    plt.figure(figsize=(8, 6))
    plt.plot(range(num_queries + 1), min_f_values, marker='o', linestyle='-', color='b')
    plt.xlabel('Iteration')
    plt.ylabel('Minimum f(x)')
    plt.title(f'Minimum f(x) vs Iteration (Run {run + 1})')
    plt.grid(True)
    plt.savefig(f'min_f_vs_iteration_run_{run + 1}.png')
    plt.close()

# Convert to numpy array for easier computation
all_min_f_values = np.array(all_min_f_values)  # Shape: (num_runs, num_queries + 1)

# Compute mean, std, and 95% CI
mean_f = np.mean(all_min_f_values, axis=0)
std_f = np.std(all_min_f_values, axis=0)
ci_95 = 1.96 * std_f / np.sqrt(num_runs)  # 95% CI: z=1.96 for normal distribution

# Plot convergence with mean, std, and CI
plt.figure(figsize=(10, 6))
iterations = range(num_queries + 1)

# Plot mean
plt.plot(iterations, mean_f, marker='o', linestyle='-', color='b', label='Mean Minimum CLEAR f(x)')

# Plot 95% CI
plt.fill_between(
    iterations,
    mean_f - ci_95,
    mean_f + ci_95,
    color='b',
    alpha=0.2,
    label='95% Confidence Interval'
)

# Plot mean ± std
plt.fill_between(
    iterations,
    mean_f - std_f,
    mean_f + std_f,
    color='g',
    alpha=0.1,
    label='Mean ± Std'
)

plt.xlabel('Iteration')
plt.ylabel('Minimum f(x)')
plt.title('Convergence Plot: Mean, Std, and 95% CI over 10 Runs (Branin)')
plt.grid(True)
plt.legend()
plt.savefig('convergence_plot.png')
plt.close()


Run 1/10
Initial points (x1, x2, f(x)):
tensor([[ 4.2204,  5.7152, 22.5310],
        [ 4.5567,  7.1169, 40.8511],
        [ 5.7039,  9.2855, 84.6316],
        [ 1.6380,  1.4365, 14.6597],
        [ 4.2124,  0.8599,  5.9265],
        [ 3.4857,  7.9984, 36.6794],
        [ 0.8508, 13.6327, 95.4217],
        [ 3.0005, 10.6101, 68.1029],
        [ 5.6740,  3.0755, 21.6653],
        [-0.3833, 14.7129, 84.2555]])


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 0, incumbent x=(4.2124, 0.8599), f(x)=5.9265


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 1, incumbent x=(4.2124, 0.8599), f(x)=5.9265


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 2, incumbent x=(4.2124, 0.8599), f(x)=5.9265


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 3, incumbent x=(4.2124, 0.8599), f(x)=5.9265


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 4, incumbent x=(4.2124, 0.8599), f(x)=5.9265


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 5, incumbent x=(3.5222, 1.5588), f(x)=1.2770


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 6, incumbent x=(3.5222, 1.5588), f(x)=1.2770


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 7, incumbent x=(3.3198, 1.8542), f(x)=0.6317


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 8, incumbent x=(3.3198, 1.8542), f(x)=0.6317


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 9, incumbent x=(3.3198, 1.8542), f(x)=0.6317


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 10, incumbent x=(3.3198, 1.8542), f(x)=0.6317


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 11, incumbent x=(3.3198, 1.8542), f(x)=0.6317


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 12, incumbent x=(3.3198, 1.8542), f(x)=0.6317


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 13, incumbent x=(3.3198, 1.8542), f(x)=0.6317


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 14, incumbent x=(3.3198, 1.8542), f(x)=0.6317


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 15, incumbent x=(3.3198, 1.8542), f(x)=0.6317


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 16, incumbent x=(9.3518, 2.6374), f(x)=0.4733


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 17, incumbent x=(9.3518, 2.6374), f(x)=0.4733


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 18, incumbent x=(9.3518, 2.6374), f(x)=0.4733


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 19, incumbent x=(9.3518, 2.6374), f(x)=0.4733


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]


Run 2/10
Initial points (x1, x2, f(x)):
tensor([[ -4.9360,   1.5835, 249.9045],
        [ -0.7124,   0.4043,  63.4390],
        [  2.0742,   0.9017,  10.9036],
        [  6.5780,  11.1555, 119.8867],
        [  3.9163,  13.3179, 136.9913],
        [  1.7655,  11.9924,  78.6948],
        [ -2.7524,   6.0220,  29.6015],
        [ -4.1873,   6.8911,  69.8027],
        [ -2.3659,  14.2377,  17.2006],
        [  7.7098,  13.1228, 148.6098]])


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 0, incumbent x=(2.0742, 0.9017), f(x)=10.9036


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 1, incumbent x=(3.9416, 1.5774), f(x)=3.3344


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 2, incumbent x=(3.9416, 1.5774), f(x)=3.3344


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 3, incumbent x=(3.9416, 1.5774), f(x)=3.3344


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 4, incumbent x=(2.9546, 2.7144), f(x)=0.6489


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 5, incumbent x=(2.9546, 2.7144), f(x)=0.6489


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 6, incumbent x=(2.9546, 2.7144), f(x)=0.6489


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 7, incumbent x=(2.9546, 2.7144), f(x)=0.6489


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 8, incumbent x=(2.9546, 2.7144), f(x)=0.6489


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 9, incumbent x=(2.9546, 2.7144), f(x)=0.6489


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 10, incumbent x=(2.9546, 2.7144), f(x)=0.6489


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 11, incumbent x=(2.9546, 2.7144), f(x)=0.6489


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 12, incumbent x=(2.9546, 2.7144), f(x)=0.6489


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 13, incumbent x=(2.9546, 2.7144), f(x)=0.6489


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 14, incumbent x=(2.9546, 2.7144), f(x)=0.6489


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 15, incumbent x=(2.9546, 2.7144), f(x)=0.6489


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 16, incumbent x=(2.9546, 2.7144), f(x)=0.6489


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 17, incumbent x=(2.9546, 2.7144), f(x)=0.6489


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 18, incumbent x=(2.9546, 2.7144), f(x)=0.6489


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 19, incumbent x=(2.9546, 2.7144), f(x)=0.6489


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]


Run 3/10
Initial points (x1, x2, f(x)):
tensor([[ 3.3946e+00,  8.3864e+00,  4.0399e+01],
        [-3.6281e+00,  3.1500e+00,  1.0811e+02],
        [-4.8921e+00,  5.8443e-01,  2.7719e+02],
        [ 9.8934e+00,  1.3697e+01,  1.1803e+02],
        [ 4.2787e+00,  1.4616e+01,  1.7654e+02],
        [-2.1632e-01,  3.2224e+00,  2.9162e+01],
        [ 8.8939e+00,  7.1028e+00,  2.7113e+01],
        [ 3.9242e+00,  1.1934e+01,  1.0703e+02],
        [ 6.4523e+00,  3.2055e+00,  2.3860e+01],
        [-4.0053e-01,  5.7830e-01,  5.5807e+01]])


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 0, incumbent x=(6.4523, 3.2055), f(x)=23.8604


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 1, incumbent x=(3.2352, 1.5590), f(x)=0.8549


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 2, incumbent x=(3.2352, 1.5590), f(x)=0.8549


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 3, incumbent x=(3.2352, 1.5590), f(x)=0.8549


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 4, incumbent x=(3.2352, 1.5590), f(x)=0.8549


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 5, incumbent x=(3.3202, 1.7435), f(x)=0.7077


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 6, incumbent x=(3.3202, 1.7435), f(x)=0.7077


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 7, incumbent x=(3.3202, 1.7435), f(x)=0.7077


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 8, incumbent x=(3.3202, 1.7435), f(x)=0.7077


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 9, incumbent x=(3.2694, 1.8193), f(x)=0.6045


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 10, incumbent x=(-3.1486, 12.3875), f(x)=0.4073


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 11, incumbent x=(-3.1486, 12.3875), f(x)=0.4073


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 12, incumbent x=(-3.1486, 12.3875), f(x)=0.4073


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 13, incumbent x=(-3.1486, 12.3875), f(x)=0.4073


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 14, incumbent x=(-3.1486, 12.3875), f(x)=0.4073


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 15, incumbent x=(-3.1486, 12.3875), f(x)=0.4073


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 16, incumbent x=(-3.1486, 12.3875), f(x)=0.4073


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 17, incumbent x=(-3.1486, 12.3875), f(x)=0.4073


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 18, incumbent x=(-3.1486, 12.3875), f(x)=0.4073


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 19, incumbent x=(-3.1486, 12.3875), f(x)=0.4073


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]


Run 4/10
Initial points (x1, x2, f(x)):
tensor([[  7.4538,   1.8917,  14.0744],
        [  8.6120,  12.2989, 112.0609],
        [  8.8016,   1.7497,   2.2655],
        [ -2.5341,  11.0688,   2.1582],
        [ -4.5010,  14.9128,   8.7391],
        [  4.0964,   8.4686,  50.9707],
        [ -3.9138,   9.8901,  21.7648],
        [  5.7251,   8.6899,  75.4113],
        [  9.7139,   9.7524,  50.1147],
        [ -4.1505,  13.8017,   5.9438]])


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 0, incumbent x=(-2.5341, 11.0688), f(x)=2.1582


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 1, incumbent x=(-2.5341, 11.0688), f(x)=2.1582


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 2, incumbent x=(-2.5341, 11.0688), f(x)=2.1582


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 3, incumbent x=(-2.5341, 11.0688), f(x)=2.1582


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 4, incumbent x=(9.0224, 1.7804), f(x)=1.3062


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 5, incumbent x=(9.2892, 1.8292), f(x)=0.7710


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 6, incumbent x=(9.2835, 1.9030), f(x)=0.7010


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 7, incumbent x=(-3.1321, 11.7657), f(x)=0.6350


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 8, incumbent x=(9.3670, 2.0794), f(x)=0.5345


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 9, incumbent x=(9.3898, 2.1717), f(x)=0.4788


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 10, incumbent x=(9.3898, 2.1717), f(x)=0.4788


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 11, incumbent x=(9.3898, 2.1717), f(x)=0.4788


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 12, incumbent x=(9.3898, 2.1717), f(x)=0.4788


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 13, incumbent x=(9.3898, 2.1717), f(x)=0.4788


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 14, incumbent x=(9.3898, 2.1717), f(x)=0.4788


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 15, incumbent x=(9.3898, 2.1717), f(x)=0.4788


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 16, incumbent x=(9.4398, 2.2347), f(x)=0.4630


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 17, incumbent x=(9.4398, 2.2347), f(x)=0.4630


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 18, incumbent x=(9.4398, 2.2347), f(x)=0.4630


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 19, incumbent x=(9.4398, 2.2347), f(x)=0.4630


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]


Run 5/10
Initial points (x1, x2, f(x)):
tensor([[ 3.5830e+00,  8.3081e+00,  4.1668e+01],
        [ 9.8024e+00,  9.1204e+00,  4.0871e+01],
        [-1.4802e+00,  6.7377e+00,  1.4483e+01],
        [ 5.1150e+00,  1.1220e+01,  1.1338e+02],
        [ 3.4016e+00,  2.5107e+00,  9.0539e-01],
        [-5.3883e-05,  6.9713e+00,  2.0545e+01],
        [ 4.4987e+00,  1.1539e+01,  1.0965e+02],
        [-1.7795e+00,  1.1722e+01,  1.4167e+01],
        [ 7.9661e+00,  9.0776e+00,  6.6051e+01],
        [ 4.7461e-01,  3.8037e+00,  2.0702e+01]])


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 0, incumbent x=(3.4016, 2.5107), f(x)=0.9054


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 1, incumbent x=(3.4016, 2.5107), f(x)=0.9054


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 2, incumbent x=(3.3915, 1.6643), f(x)=0.8758


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 3, incumbent x=(3.3915, 1.6643), f(x)=0.8758


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 4, incumbent x=(3.1223, 2.5410), f(x)=0.4626


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 5, incumbent x=(3.1223, 2.5410), f(x)=0.4626


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 6, incumbent x=(3.1223, 2.5410), f(x)=0.4626


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 7, incumbent x=(3.1223, 2.5410), f(x)=0.4626


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 8, incumbent x=(3.1223, 2.5410), f(x)=0.4626


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 9, incumbent x=(3.1223, 2.5410), f(x)=0.4626


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 10, incumbent x=(3.1223, 2.5410), f(x)=0.4626


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 11, incumbent x=(3.1223, 2.5410), f(x)=0.4626


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 12, incumbent x=(3.1223, 2.5410), f(x)=0.4626


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 13, incumbent x=(3.1223, 2.5410), f(x)=0.4626


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 14, incumbent x=(3.1223, 2.5410), f(x)=0.4626


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 15, incumbent x=(3.1223, 2.5410), f(x)=0.4626


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 16, incumbent x=(3.1223, 2.5410), f(x)=0.4626


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 17, incumbent x=(3.1223, 2.5410), f(x)=0.4626


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 18, incumbent x=(3.1223, 2.5410), f(x)=0.4626


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 19, incumbent x=(3.1223, 2.5410), f(x)=0.4626


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]


Run 6/10
Initial points (x1, x2, f(x)):
tensor([[ 3.0238,  2.9820,  0.8407],
        [ 4.8882,  9.8534, 84.7195],
        [-1.5086,  6.3759, 15.9751],
        [-1.8937,  9.4460,  6.9539],
        [ 0.4797, 12.7690, 74.8106],
        [ 7.8241,  8.2640, 56.6383],
        [-0.6974,  3.0948, 33.9903],
        [ 1.6764,  5.3893, 11.8588],
        [ 5.8057,  1.0958, 18.5285],
        [ 9.5488,  1.6168,  1.4025]])


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 0, incumbent x=(3.0238, 2.9820), f(x)=0.8407


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 1, incumbent x=(3.0238, 2.9820), f(x)=0.8407


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 2, incumbent x=(3.0238, 2.9820), f(x)=0.8407


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 3, incumbent x=(3.0238, 2.9820), f(x)=0.8407


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 4, incumbent x=(9.3780, 1.8231), f(x)=0.7838


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 5, incumbent x=(9.3590, 1.8312), f(x)=0.7655


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 6, incumbent x=(3.0051, 2.8458), f(x)=0.7006


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 7, incumbent x=(3.0015, 2.8195), f(x)=0.6792


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 8, incumbent x=(2.9959, 2.7796), f(x)=0.6503


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 9, incumbent x=(2.9882, 2.7246), f(x)=0.6175


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 10, incumbent x=(2.9797, 2.6657), f(x)=0.5916


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 11, incumbent x=(2.9725, 2.6161), f(x)=0.5771


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 12, incumbent x=(2.9668, 2.5789), f(x)=0.5709


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 13, incumbent x=(2.9668, 2.5789), f(x)=0.5709


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 14, incumbent x=(2.9825, 2.5562), f(x)=0.5428


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 15, incumbent x=(3.0407, 2.5327), f(x)=0.4783


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 16, incumbent x=(3.0843, 2.5243), f(x)=0.4554


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 17, incumbent x=(3.1145, 2.5202), f(x)=0.4516


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 18, incumbent x=(3.1145, 2.5202), f(x)=0.4516


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 19, incumbent x=(3.1192, 2.5184), f(x)=0.4513


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]


Run 7/10
Initial points (x1, x2, f(x)):
tensor([[  3.9689,  12.6794, 123.6489],
        [  9.1962,   4.4480,   5.3092],
        [  2.7070,   9.6652,  50.6676],
        [  8.4858,   0.2113,   6.8425],
        [  3.6768,   1.8271,   1.7451],
        [  8.7714,  10.2080,  70.0917],
        [ -1.9997,   1.6816,  70.2890],
        [ -4.9708,  13.3924,  26.2233],
        [  7.0707,   3.8202,  23.6133],
        [  2.0245,   2.5234,   6.4062]])


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 0, incumbent x=(3.6768, 1.8271), f(x)=1.7451


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 1, incumbent x=(3.4298, 1.7759), f(x)=0.8752


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 2, incumbent x=(3.4146, 1.7728), f(x)=0.8429


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 3, incumbent x=(3.3813, 1.7655), f(x)=0.7813


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 4, incumbent x=(3.3813, 1.7655), f(x)=0.7813


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 5, incumbent x=(3.3363, 1.7553), f(x)=0.7183


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 6, incumbent x=(3.2969, 1.7462), f(x)=0.6823


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 7, incumbent x=(3.2671, 1.7383), f(x)=0.6678


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 8, incumbent x=(3.2671, 1.7383), f(x)=0.6678


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 9, incumbent x=(3.2671, 1.7383), f(x)=0.6678


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 10, incumbent x=(3.2504, 1.7559), f(x)=0.6446


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 11, incumbent x=(3.2405, 1.7972), f(x)=0.6064


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 12, incumbent x=(3.2346, 1.8361), f(x)=0.5744


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 13, incumbent x=(3.2346, 1.8361), f(x)=0.5744


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 14, incumbent x=(3.2346, 1.8361), f(x)=0.5744


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 15, incumbent x=(3.2316, 1.8810), f(x)=0.5423


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 16, incumbent x=(3.2334, 1.9376), f(x)=0.5095


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 17, incumbent x=(3.2372, 1.9993), f(x)=0.4826


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 18, incumbent x=(3.2473, 2.0560), f(x)=0.4705


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 19, incumbent x=(3.2524, 2.0970), f(x)=0.4654


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]


Run 8/10
Initial points (x1, x2, f(x)):
tensor([[  4.8368,   4.5303,  21.4704],
        [  2.1984,  11.6606,  77.2103],
        [  8.7695,  13.9655, 146.0942],
        [ -1.0946,  14.3014,  55.4190],
        [  0.7066,   6.1565,  18.7833],
        [  9.2653,   8.5294,  38.7823],
        [ -2.9286,   3.1030,  75.7132],
        [  2.7085,   7.2750,  22.7956],
        [  2.7891,   5.2017,   7.9353],
        [  1.7148,   9.4733,  42.5253]])


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 0, incumbent x=(2.7891, 5.2017), f(x)=7.9353


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 1, incumbent x=(2.2317, 4.9279), f(x)=7.4782


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 2, incumbent x=(2.2146, 4.6174), f(x)=6.5119


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 3, incumbent x=(2.5317, 4.1742), f(x)=4.0211


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 4, incumbent x=(2.9173, 1.5778), f(x)=1.4105


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 5, incumbent x=(2.9173, 1.5778), f(x)=1.4105


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 6, incumbent x=(2.9173, 1.5778), f(x)=1.4105


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 7, incumbent x=(2.9878, 1.9217), f(x)=0.7382


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 8, incumbent x=(2.9878, 1.9217), f(x)=0.7382


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 9, incumbent x=(2.9878, 1.9217), f(x)=0.7382


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 10, incumbent x=(2.9878, 1.9217), f(x)=0.7382


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 11, incumbent x=(2.9878, 1.9217), f(x)=0.7382


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 12, incumbent x=(2.9999, 2.7451), f(x)=0.6216


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 13, incumbent x=(2.9999, 2.7451), f(x)=0.6216


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 14, incumbent x=(2.9999, 2.7451), f(x)=0.6216


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 15, incumbent x=(9.3220, 2.6845), f(x)=0.5354


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 16, incumbent x=(9.3220, 2.6845), f(x)=0.5354


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 17, incumbent x=(9.3220, 2.6845), f(x)=0.5354


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 18, incumbent x=(9.3220, 2.6845), f(x)=0.5354


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 19, incumbent x=(3.2018, 2.3984), f(x)=0.4442


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]


Run 9/10
Initial points (x1, x2, f(x)):
tensor([[  1.8713,   7.2428,  21.3612],
        [ -0.3125,   9.2253,  26.5099],
        [ -1.7908,   6.1774,  17.4343],
        [  5.4069,  14.5396, 194.8577],
        [  4.2669,   4.9555,  17.3854],
        [  3.2191,   6.6595,  20.1772],
        [  5.5614,   8.3588,  69.2556],
        [  5.4379,  14.7739, 201.5638],
        [ -0.6144,   7.2349,  17.8895],
        [  4.2249,   7.4510,  39.9500]])


/opt/anaconda3/envs/meng/lib/python3.10/site-packages/botorch/optim/optimize.py:331: BadInitialCandidatesWarning: Unable to find non-zero acquisition function values - initial conditions are being selected randomly.
  generated_initial_conditions = opt_inputs.get_ic_generator()(


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 0, incumbent x=(4.2669, 4.9555), f(x)=17.3854


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 1, incumbent x=(4.2669, 4.9555), f(x)=17.3854


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 2, incumbent x=(4.2669, 4.9555), f(x)=17.3854


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 3, incumbent x=(4.2669, 4.9555), f(x)=17.3854


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 4, incumbent x=(8.4267, 0.1401), f(x)=7.4264


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 5, incumbent x=(8.4267, 0.1401), f(x)=7.4264


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 6, incumbent x=(8.4267, 0.1401), f(x)=7.4264


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 7, incumbent x=(8.4267, 0.1401), f(x)=7.4264


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 8, incumbent x=(9.0584, 0.0000), f(x)=5.8019


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 9, incumbent x=(9.0584, 0.0000), f(x)=5.8019


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 10, incumbent x=(9.0584, 0.0000), f(x)=5.8019


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 11, incumbent x=(10.0000, 4.4219), f(x)=3.9567


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 12, incumbent x=(10.0000, 4.4219), f(x)=3.9567


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 13, incumbent x=(10.0000, 4.2987), f(x)=3.6221


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 14, incumbent x=(10.0000, 3.5613), f(x)=2.2549


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 15, incumbent x=(10.0000, 3.5613), f(x)=2.2549


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 16, incumbent x=(9.8191, 3.3761), f(x)=1.4355


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 17, incumbent x=(9.8191, 3.3761), f(x)=1.4355


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 18, incumbent x=(9.4229, 2.9458), f(x)=0.6210


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 19, incumbent x=(9.4229, 2.9458), f(x)=0.6210


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]


Run 10/10
Initial points (x1, x2, f(x)):
tensor([[ -2.7644,   7.2983,  17.7891],
        [  9.7849,   2.5260,   1.0865],
        [  3.7592,  10.4040,  75.4678],
        [  3.7463,   1.9266,   2.1063],
        [  3.5818,  13.8726, 143.3018],
        [ -0.9599,  11.7369,  32.2359],
        [ -0.9217,   6.9485,  16.1989],
        [  6.5070,   7.5364,  60.6150],
        [ -3.4625,  11.4000,   3.6418],
        [  7.0531,  11.4795, 122.5385]])


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 0, incumbent x=(9.7849, 2.5260), f(x)=1.0865


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 1, incumbent x=(9.7849, 2.5260), f(x)=1.0865


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 2, incumbent x=(9.7843, 2.5262), f(x)=1.0842


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 3, incumbent x=(9.7708, 2.5300), f(x)=1.0306


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 4, incumbent x=(9.7260, 2.5429), f(x)=0.8693


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 5, incumbent x=(9.7260, 2.5429), f(x)=0.8693


/opt/anaconda3/envs/meng/lib/python3.10/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-06 to the diagonal
  warnings.warn(
/opt/anaconda3/envs/meng/lib/python3.10/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-05 to the diagonal
  warnings.warn(
/opt/anaconda3/envs/meng/lib/python3.10/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-04 to the diagonal
  warnings.warn(


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 6, incumbent x=(9.6851, 2.5553), f(x)=0.7432


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 7, incumbent x=(9.6477, 2.5665), f(x)=0.6461


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 8, incumbent x=(9.6010, 2.5912), f(x)=0.5480


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 9, incumbent x=(9.5663, 2.6083), f(x)=0.4940


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 10, incumbent x=(9.5328, 2.6263), f(x)=0.4573


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 11, incumbent x=(9.5054, 2.6404), f(x)=0.4384


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 12, incumbent x=(9.4819, 2.6480), f(x)=0.4290


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 13, incumbent x=(9.4674, 2.6371), f(x)=0.4225


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 14, incumbent x=(9.4589, 2.6213), f(x)=0.4173


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 15, incumbent x=(9.4562, 2.6079), f(x)=0.4139


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 16, incumbent x=(9.4562, 2.6079), f(x)=0.4139


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 17, incumbent x=(9.4245, 2.5903), f(x)=0.4112


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 18, incumbent x=(9.4472, 2.5884), f(x)=0.4092


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]

Iteration 19, incumbent x=(9.4468, 2.5813), f(x)=0.4079


Training GP:   0%|          | 0/500 [00:00<?, ?it/s]